import json


user_fixups = {
    "File:22pommes.vmod": 'Gaet',
    "File:2-BAOR 1-1.vmdx": 'Rfdoane',
    "File:Aev31f.vmod": 'Mbeninger',
    "File:Arriala.vmod": 'Gaetbe',
    "File:At the Gates of Loyang.vmod": 'Soft-bug',
    "File:BattleForNormandy 2.vmod": 'Joel_Toppen',
    "File:British-USMC.vmdx": 'Rfdoane',
    "File:BSG Pyramid.vmod": 'Soft-bug',
    "File:Burma v1 2.vmod": 'Kishel',
    "File:Burma v1 31.vmod": 'Jeux12sl',
    "File:Burma V1.33.vmod": 'Jeux12sl',
    "File:Burma v1 34.vmod": 'DaveyJones',
    "File:Carcassonne-2.0.vmod": 'ColtsFan76',
    "File:Carcassonne-Simple.vmod": 'Sultan',
    "File:Circus1.2.vmod": 'Skalla',
    "File:Dealer McDope 1.0 .vmod": 'burdick.ip.research',
    "File:End of Empire v1 3.vmod": 'Tswider2',
    "File:Epic 0 2.vmod": 'Austerity',
    "File:Espana1936v12.vmod": 'Norovirus',
    "File:Espana1936.vmod": 'Norovirus',
    "File:Espinosa v1.1.vmod": 'Taikunkikun',
    "File:EuroFront II v1.8.vmod": 'bennyb',
    "File:EV-1.01.vmod": 'TeTeT',
    "File:EV-1.0.vmod": 'TeTeT',
    "File:GBoH-Chandragupta 2.0.vmod": 'Alfonso',
    "File:GBoH RAN.vmod": 'Grenadyer',
    "File:GhostStories 117.vmod": 'Waddball',
    "File:GhostStories 118.vmod": 'Waddball',
    "File:IDF.vmdx": 'Rfdoane',
    "File:IMPORTANT - readme.txt": 'Rfdoane',
    "File:Khaki1.vmod": 'Dmart',
    "File:LMaps-2-FRG.vmdx": 'Rfdoane',
    "File:LMaps-3-BOAR.vmdx": 'Rfdoane',
    "File:LoanoVassal.vmod": 'Bubulle',
    "File:Machiavelli.vmod": 'Mycenae',
    "File:Manv1b.vmod": 'Mbeninger',
    "File:MarcoPolo.vmod": 'Yuyu',
    "File:Marengo 0.3.vmod": 'Bsmith',
    "File:Maria User Guide.pdf": 'SteveBish',
    "File:MBT-IDF.vmod": 'Rfdoane',
    "File:Mesopotamia v1 01.vmod": 'Rwein',
    "File:Misterio.vmod": 'Yuyu',
    "File:Multi.vmod": 'Thorndraco',
    "File:Nadir DTP Pack.vmdx": 'Rfdoane',
    "File:Naipe en la Ruta de la Selva.vmod": 'Packonn',
    "File:Not Go v1.2.vmod": 'Narfanator',
    "File:OCOWargamer41a.vmod": 'Mwilding',
    "File:OdiseaEspacial.vmod": 'Yuyu',
    "File:Offrandes.vmod": 'Gaetbe',
    "File:Ogremanual.zip": 'Zass',
    "File:OGRE.vmod": 'Zass',
    "File:Op Felix.vmod": 'Jmlima',
    "File:OpM v1 0.vmod": 'Kishel',
    "File:Othello-Reversi.vmod": 'Aidendouglass',
    "File:Outlaws.vmod": 'Jerry_Tresman',
    "File:Overthetop 0.11.zip": 'Josh_Laverty',
    "File:Overthetop 0.12.vmod": 'Josh_Laverty',
    "File:Over the top rules v011.pdf": 'Josh_Laverty',
    "File:Pacific Victory v1 1 1.vmod": 'Fbedard24',
    "File:PaxRomana4.1.vmod": 'Kcoombs',
    "File:Playing Cards.vmod": 'Tadufre',
    "File:Pocketrockets.vmod": 'Gaetbe',
    "File:Price of Freedom v1.0.vmod": 'Kcoombs',
    "File:Princes of the Renaissance-0.2.vmod": 'Quicksabre',
    "File:Project Discovery.vmod": 'Srmansfield',
    "File:PrussiasDefiantStand-v5.vmod": 'Shilinski',
    "File:PTA Vassal Sept 17 2008.vmod": 'Brennenreece',
    "File:Quintet v1 0.vmod": 'Brian448',
    "File:Raceday.vmod": 'Deaneubanks',
    "File:Race for berlin 1.1.vmod": 'Francois_Xavier_Euze',
    "File:RedDragonInn v1 6.vmod": 'Neumannium',
    "File:Revolutionary Road B2C R1.01.vmod": 'Jardic',
    "File:Rommel-Desert-v6.vmod": 'shilinski',
    "File:Rommel-Desert-v7.vmod": 'shilinski',
    "File:Royal Tank Corp v1.vmod": 'Dirk_Heinz',
    "File:RustleMania v0.2.1.vmod": 'Kcoombs',
    "File:Silentdeath OD 1.02.vmod": 'Dave_Faucher',
    "File:SOS version history.zip": 'Brent_Easton',
    "File:Spanish-Eagles-Vassal-1.0.vmod": 'Kcoombs',
    "File:Starmada AE.vmod": 'MadSeason',
    "File:Starmada Vassal Playing Guide.pdf": 'MadSeason',
    "File:Starmada.vmod": 'Jefferyschutt',
    "File:Starvation Island Ver1.vmod": 'Mark_Evans',
    "File:Sticks and Stones.vmod": 'Xavier',
    "File:StormOverStalingrad v12.vmod": 'Brent_Easton',
    "File:StradaRomana.vmod": 'Gaetbe',
    "File:Strategos 0 1.vmod": 'IrishBouzouki',
    "File:Strategos 0 2.vmod": 'IrishBouzouki',
    "File:Succession Wars1.01.vmod": 'Skorpio',
    "File:TarotGame.vmod": 'Tarotgames',
    "File:Terrain Pack.vmdx": 'Rfdoane',
    "File:The Rum Run-0.1.vmod": 'Alex_Coulombe',
    "File:Thunder at Cassino 1.2.vmod": 'Kaiman',
    "File:Thunder at Cassino.pdf": 'Kaiman',
    "File:Thunder at Cassino.vmod": 'Kaiman',
    "File:Tpovs 2.0.1.vmod": 'Harm',
    "File:Turret MOD.vmdx": 'Richz99',
    "File:Tutorial Link.txt": 'Soft-bug',
    "File:Urrah!v13.vmod": 'Yangtze',
    "File:Vampires Dance.vmod": 'Soft-bug',
    "File:Version History.txt": 'Rfdoane',
    "File:Victory v0.7.vmod": 'Stailinn',
    "File:Wolf.vmod": 'Gaetbe',
    "File:World Killer v1.0 09 24 10.vmod": 'Brian448',
    "File:YKv2 1.vmod": 'Kishel',
    "File:YKv2.vmod": 'Kishel',
    "File:Zimp.vmod": 'Soft-bug',
    "File:Cannonball Colony.pdf": 'Soft-bug',
    "File:Cannonball Colony.vmod": 'Soft-bug',
    "File:City of Guilds.vmod": 'Soft-bug',
    "File:Commodore.vmod": 'Soft-bug',
    "File:Delve Dice Game.vmod": 'Soft-bug',
    "File:Dune Express.vmod": 'Soft-bug',
    "File:EC decks Package.zip": 'Soft-bug',
    "File:Eatg1 4.vmod": 'Kurtmeyer41',
    "File:En Garde v1 04.vmod": 'Rwein',
    "File:AH ED.vmod": 'Fleanbilly',
    "File:KS Galactic Adventures.vmod": 'Mandalorien',
    "File:KS Galactic Adventures Manual V1.01 Fr.pdf": 'Mandalorien',
    "File:Link.txt": 'Soft-bug',
    "File:GE Vassal EN.pdf": 'Soft-bug',
    "File:GalacticEmperor.vmod": 'Soft-bug',
    "File:Galaxy of D.vmod": 'Soft-bug',
    "File:Go.vmod": 'Soft-bug',
    "File:Hibernia.vmod": 'Soft-bug',
    "File:HT beta 4b.vmod": 'Blankshield',
    "File:Huuue.vmod": 'Soft-bug',
    "File:Aide de jeu huuue.pdf": 'Soft-bug',
    "File:Iliad.vmod": 'Soft-bug',
    "File:InfinityVassalModule.0 94.vmod": 'DreamSlayer',
    "File:Infinity v0.4.vmod": 'LordJesse',
    "File:Kahmate rules.pdf": 'Gaetbe',
    "File:Kahmate.vmod": 'Gaetbe',
    "File:LeapingLemmings.vmod": 'Gaetbe',
    "File:Marche Samarkand.vmod": 'Soft-bug',
    "File:Faiseurs Univers.vmod": 'Soft-bug',
    "File:Tutorial Video Link.txt": 'Soft-bug',
    "File:School Idol Hell.vmod": 'Floesnotal',
    "File:North Korea Nuclear Crisis.vmod": 'JulianSC',
    "File:Pc Decks.zip": 'Soft-bug',
    "File:Panzer Clash.vmod": 'Soft-bug',
    "File:Panzers.vmod": 'Soft-bug',
    "File:Regatta.vmod": 'Gaetbe',
    "File:RichardIII v6.vmod": 'Shilinski',
    "File:Sagunto2.vmod": 'Horsa',
    "File:SaguntoHelp&Tables.zip": 'Horsa',
    "File:Stalins War v19.vmod": 'Pmarjora',
    "File:Stalins War v18.vmod": 'Pmarjora',
    "File:Stand at mortain.vmod": 'Kjuice',
    "File:Dungeoneer-Beta.vmod": 'DInDenver',
    "File:Trollland.vmod": 'Gaetbe',
    "File:Tutorial Video link.txt": 'Soft-bug',
    "File:Cape & Epee.vmod": 'Gaetbe',
    "File:Trader.vmod": 'Gaetbe',
    "File:Chabyrinthe.vmod": 'Gaetbe',
    "File:Senet.vmod": 'Yuyu',
    "File:Admiralty.vmod": 'Ichibrothers',
    "File:Fal01.vmod": 'Jeibel',
    "File:ApocalypseOfSteel.vmod": 'Ruschak',
    "File:3W BattleCry!.vmod": 'Cantata',
    "File:Salvo-0.2.vmod": 'Ramjack1973',
    "File:Salvo.vmod": 'Ramjack1973',
    "File:Etosetup.vsav": 'Mbeninger',
    "File:Bg2eto.vmod": 'Mbeninger',
    "File:Etosetup.vsav": 'Mbeninger',
    "File:Bridge.vmod": 'Dcholtx',
    "File:Conflict.vmod": 'Brigz',
    "File:Dusthalo.vmod": 'Postrodent',
    "File:DHrules-new.zip": 'Postrodent',
    "File:EOTID.vmod": 'GJK',
    "File:AT-Start.vsav": 'GJK',
    "File:F\u00e9odalit\u00e9.vmod": 'Mbeninger',
    "File:Using the F\u00e9odalit\u00e9 module.pdf": 'Mbeninger',
    "File:First Team 11a.vmod": 'Theaney',
    "File:First Team rules.pdf": 'Theaney',
    "File:First Team p15.pdf": 'Theaney',
    "File:THW.vmod": 'ThePup',
    "File:Germania.vmod": 'Donegal',
    "File:GuadalcanalInfoFiles.zip": 'Charles_McLellan',
    "File:+Guad.txt": 'Charles_McLellan',
    "File:GuadMaster.vmod": 'Charles_McLellan',
    "File:Halebarde&gonfanon.vmod": 'Eforgeot',
    "File:H&g start.vlog": 'Eforgeot',
    "File:H&g tour part1.vlog": 'Eforgeot',
    "File:HFP Wargamer 39b.vmod": 'Mwilding',
    "File:Hera and Zeus.vmod": 'Donegal',
    "File:Heroclix-02.vmod": 'Roguetrada',
    "File:Iberos.vmod": 'Donegal',
    "File:Justinian.vmod": 'Donegal',
    "File:Khas-Rules.pdf": 'Natural20',
    "File:Khas.vmod": 'Natural20',
    "File:Klinzha.vmod": 'Joekid',
    "File:Trojanwar.vmod": 'Mbeninger',
    "File:Troie notes.pdf": 'Mbeninger',
    "File:VLOS05.vmod": 'YojimboUsaka',
    "File:MagicRealm.vmod": 'PieroErminio.Piotti',
    "File:Monsterpocalypse 1.00.vmod": 'Arizzle',
    "File:Monsterpocalypse 1.01.vmod": 'Arizzle',
    "File:Monsterpocalypse 1.00 Instructions.txt": 'Arizzle',
    "File:Monsterpocalypse Success Calculator.zip": 'Arizzle',
    "File:Mosbys raiders.vmod": 'Toshikazu',
    "File:Pegasus Bridge Mod.vmod": 'Blackhorse',
    "File:RaceForTunis.vmod": 'Nadir.elfarra',
    "File:Raj.vmod": 'Rk1',
    "File:Rswe.vmod": 'Alsandor',
    "File:RoadRage1.3.vmod": 'BetaMale',
    "File:RoadRage1.4a.vmod": 'BetaMale',
    "File:RmR.vmod": 'VassalJason',
    "File:VMidway.vmod": 'Toze_Santos',
    "File:Vinci.vmod": 'Glocko',
    "File:Vjw.vmod": 'Takagi',
    "File:Vino.vmod": 'Glocko',
    "File:Vmbb.vmod": 'Mbeninger',
    "File:Speedcircuit.vmod": 'Skalla',
    "File:Targui.vmod": 'Gorodoff',
    "File:Alamo.vmod": 'GJK',
    "File:Alamo114.vmod": 'GJK',
    "File:Rise of the Roman Republic.vmod": 'Kcoombs',
    "File:AirPower.vmod": 'Jean-claude.lallemant',
    "File:TPStalingrad.vmod": 'Toze_Santos',
    "File:BtB ver2-01.vmod": 'Alexander331bc',
    "File:War of the suns v06.vmod": 'Brent_Easton',
    "File:War of the suns v05.vmod": 'Brent_Easton',
    "File:SP II v12.vmod": 'Fgbelmon',
    "File:Risk2210.vmod": 'Natural20',
    "File:Struggle for Europe v2.1.vmod": 'Bsmith',
    "File:Perryville19.vmod": 'GJK',
    "File:Scenario 1.vsav": 'GJK',
    "File:Readme.txt": 'GJK',
    "File:Aireaters002.vmod": 'Jimu',
    "File:Aireaters006.vmod": 'Jimu',
}


def run():
    ipath = 'data/files.json'
    opath = 'data/files_fixed.json'

    with open(ipath, 'r') as f:
        p = json.load(f)

    for k, v in p.items():
        if fixup := user_fixups.get(k, None):
            v['user'] = fixup

    with open(opath, 'w') as f:
        json.dump(p, f, indent=2)


if __name__ == '__main__':
    run()
